### ISSUE TITLE
MANIFEST のファイル名記載ミス

### ISSUE THREAD

**Issue by mikoto2000** [TOPPERS-ContributedSoftware/cfg#12]
d6a03942672af55dde26b1262604f124763e887c の変更点ですが、

×: `bash.sh`
〇: `build.sh`

だと思われます。

https://github.com/TOPPERS-ContributedSoftware/cfg/commit/d6a03942672af55dde26b1262604f124763e887c#diff-0bf22fc49ca50df354c7619caaaa96d2R8

**Comment by mitsut** [comment]
@mikoto2000 対応しました。ご確認ください。

**Comment by mikoto2000** [comment]
修正ありがとうございます！
