### ISSUE TITLE
質問: ビルドするディストリビューション、gcc のバージョン指定はありますか？

### ISSUE THREAD

**Issue by mikoto2000** [TOPPERS-ContributedSoftware/cfg#6]
いくつか PR を送らせていただきましたが、私のビルド環境は以下の通りです。

- OS: Ubuntu 18.04([dockrehub の公式 Ubuntu イメージ](https://hub.docker.com/_/ubuntu)の `ubuntu:bionic` を使用)
- g++: g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- libboost-dev: 1.65.1.0ubuntu1

現状 Travis のビルドが失敗しているようですし、
「この環境でビルドできることを確認してくれ」といった条件があればお教えください。

**Comment by mitsut** [comment]
PRをマージしましたのでcloseします
