### ISSUE TITLE
ARXML の pass 2 でセグメンテーションフォルトになる直接原因の報告

### ISSUE THREAD

**Issue by mikoto2000** [TOPPERS-ContributedSoftware/cfg#9]
[workaround.hpp#L66](https://github.com/TOPPERS-ContributedSoftware/cfg/blob/master/toppers/workaround.hpp#L66) のようです。
この行を削除したところ、セグメンテーションフォルトが解消されました。

BOOST_SP_DISABLE_THREADSの参考ページ: [shared_ptr の排他制御を抑止する。 | 株式会社きじねこ](http://www.kijineko.co.jp/tech/boost-memo/lock-free-shared_ptr.html)

xerces-c のビルドオプションで、スレッドを無効にすることでも解消できるかもしれません。
(https://xerces.apache.org/xerces-c/build-3.html) (未検証)

それとは別に、[PR #3 のコメント](https://github.com/TOPPERS-ContributedSoftware/cfg/pull/3#issuecomment-457802069)にて、 5 系を使うようにすると話していたので、このワークアラウンドの根本的な見直しをすることも必要そうです。

**Comment by mitsut** [comment]
#10 PRをマージしましたので、本件はクローズにしたいと思います。
ただ、bionic環境でビルドを行うと解消されていますが、xenial環境では問題があるようです。
NG環境のバージョン情報（OSだけでなく、gcc、glibc、xercesも）を記載した上で閉じる予定です。
